# Generated by Django 3.2 on 2022-11-11 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('postalZip', models.IntegerField()),
                ('customer', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.IntegerField()),
                ('acc_num', models.CharField(max_length=20)),
                ('pan', models.CharField(max_length=30)),
                ('cvv', models.IntegerField()),
                ('customer', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.customer')),
            ],
        ),
    ]
